### ISSUE TITLE
COMO LO INSTALO? 

### ISSUE THREAD

**Issue by pitu2016** [HuayraLinux/huayra-caripela#11]
Descargue el archivo todo pero al momento de instalar me salta un error en la terminal que no se encontro el archivo el fichero...

**Comment by iglosiggio** [comment]
¿Pudiste hacer el npm install bien?

¿El binario de nwjs está en el $PATH? (Probá haciendo `which nw`

**Comment by pitu2016** [comment]
la verdad es que es la primera vez que pruebo instalar algo en huayra, no lo uso digamos pero queria usar este programa ahora,lo que hice fue poner la linea q muestra en el instructivo de la pagina de huayra:  sudo apt-get install caripela y de ahi me pone esto alumno@huayra:~$ sudo apt-get install caripela
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
E: No se ha podido localizar el paquete caripela

**Comment by iglosiggio** [comment]
Bueno, este repo es para el desarrollo de la aplicación y no tanto para el paquete mismo de huayra.

De todas formas probablemente el error sea que no están actualizados los repositorios (la lista de aplicaciones)

Probá hacer `sudo apt-get update` y después instalarlo. Una cosa que siempre está bueno usar para ver si el nombre de la aplicación es el correcto es usar `apt-cache search <nombre>`

En el caso de caripela pasa esto
```
alumno@huayra:~$ apt-cache search caripela
huayra-caripela - Permite crear personajes personalizados
caripela - Paquete transitorio para huayra-caripela
```

**Comment by iglosiggio** [comment]
Bueno, fijate que también el paquete posta es huayra-caripela, caripela quedó de una versión anterior y es de transición

**Comment by ftoledo** [comment]
¿Qué versión de Huayra tenés @pitu2016 ?

**Comment by hugoruscitti** [comment]
Lo marco como resuelto, si hay alguna novedad re-abrimos.
