### ISSUE TITLE
Falla la compilación del paquete en strider

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/huayra-caripela#13]
Parece que este paquete tiene un problema similar al que vimos en visita-hcdn: https://github.com/HuayraLinux/visita-HCDN/issues/6

http://ci.huayragnulinux.com.ar/huayralinux/huayra-caripela/

**Comment by iglosiggio** [comment]
Pasó la [build](http://ci.huayragnulinux.com.ar/huayralinux/huayra-caripela/job/57d2f8543615d50268276ec5) en el commit e9735be
