### ISSUE TITLE
Error al importar una imágen a la bilbioteca

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/huayra-caripela#4]
Si se quiere agregar una imagen al la biblioteca actual, se intenta guardar en /usr/share/caripela/src/partes/ (donde está la aplicación instalada) y se genera una excepción.
Este archivo que se importa se sebe guardar en $HOME/.caripela/partes/XXXX/archivo.svg
<pre>
Uncaught node.js Error 

Error: EACCES, permission denied '/usr/share/caripela/src/partes/1-cara/atomix-icon.png'
    at Error (native)
    at Object.fs.openSync (fs.js:441:18)
    at Object.fs.writeFileSync (fs.js:987:15)
    at HTMLInputElement.<anonymous> (file:///usr/share/caripela/src/js/controllers/EditorCtrl.js:75:16)
    at HTMLInputElement.on_click (file:///usr/share/caripela/src/js/controllers/EditorCtrl.js:199:15)
</pre>

También hay que verificar si se puede usar un .png para importar como archivo de biblioteca o tiene que ser .svg. En todo case se debe filtrar en el dialogo para seleccionar el archivo los tipos de formatos soportados.

**Comment by hugoruscitti** [comment]
dales, lo voy a mirar más tarde a ver que onda...

**Comment by dggluz** [comment]
Listo!

**Comment by hugoruscitti** [comment]
Genial!!!, gracias!

On Mon, Apr 13, 2015 at 4:23 PM, Gonzalo Gluzman <notifications@github.com>
wrote:

> Closed #4 <https://github.com/HuayraLinux/huayra-caripela/issues/4>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HuayraLinux/huayra-caripela/issues/4#event-280089981>.
>



-- 
Hugo Ruscitti

www.pilas-engine.com.ar
www.examplelab.com.ar
www.losersjuegos.com.ar
